version: '3.7'
services:
  bdd:
    container_name: gogole-map_bdd_1
    build: ./bdd
    networks:
      - back
    ports:
    - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 15s
      timeout: 5s
      retries: 3

  back:
    container_name: gogole-map_back_1
    build: ./server
    networks:
      - front
      - back
    entrypoint:
    - java
    - -jar
    - app.jar
    ports:  # use ports instead of expose to map ports
    - 8080:8080
    depends_on:
      bdd:
        condition: service_healthy


  front:
    container_name: gogole-map_front_1
    build: ./client
    networks:
      - front
    ports:
      - 3000:3000

networks:
  front:
  back: 